apiVersion: v1
kind: Service
metadata:
  name: {{ include "wecom-read-it-later.fullname" . }}
  labels:
    {{- include "wecom-read-it-later.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wecom-read-it-later.selectorLabels" . | nindent 4 }}
